<?php
/**
 * @file
 * Code for keeping sessions alive on forms.
 *
 * @author Christian Lund <christian.lund@adapt.dk>
 */


/**
 * Implements hook_menu().
 */
function sessions_keep_alive_menu() {
  $items = array();

  $items['sessions/keep/alive'] = array(
    'title' => 'Ajax callback for Sessions Keep alive',
    'description' => 'Callback for sessions keep alive ping',
    'page callback' => 'sessions_keep_alive_ajax_callback',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Callback for ajax call.
 * @return bool
 */
function sessions_keep_alive_ajax_callback() {
  return TRUE;
}

/**
 * Implements hook_form_alter().
 */
function sessions_keep_alive_form_alter(&$form, &$form_state, $form_id) {
  $forms = variable_get('sessions_keep_alive_forms');
  foreach ($forms as $delta => $form_name) {
    if ($form_id == $form_name) {
      $form['#attached']['js'][] = drupal_get_path('module', 'sessions_keep_alive') . '/js/sessions-keep-alive.js';
      $form['#attached']['js'][] = array(
        'data' => array('session_keep_alive_interval' => variable_get('sessions_keep_alive_interval', '15')),
        'type' => 'setting',
      );
    }
  }
}
