<?php
/**
 * @file
 * Code for keeping sessions alive on forms.
 *
 * @author Christian Lund <christian.lund@adapt.dk>
 */


/**
 * Implements hook_permission().
 */

function sessions_keep_alive_permission() {
  return array(
    'access sessions keep alive configuration' => array(
      'title' => t('Access sessions keep alive settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sessions_keep_alive_menu() {
  $items = array();

  $items['sessions/keep/alive'] = array(
    'title' => 'Ajax callback for Sessions Keep alive',
    'description' => 'Callback for sessions keep alive ping',
    'page callback' => 'sessions_keep_alive_ajax_callback',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  $items['admin/config/system/sessions_keep_alive'] = array(
    'title' => 'Sessions Keep alive Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sessions_keep_alive_admin_form'),
    'access arguments' => TRUE,
    'description' => 'Edit which forms should be affected.',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Callback for ajax call.
 * @return bool
 */
function sessions_keep_alive_ajax_callback() {
  return TRUE;
}


/**
 * @param $form
 * @param $form_state
 */
function sessions_keep_alive_admin_form($form, $form_state) {

  $form['sessions_keep_alive_forms'] = array(
    '#type' => 'textfield',
    '#title' => t('Forms'),
    '#default_value' => variable_get('sessions_keep_alive_forms', ''),
    '#description' => t('The forms that should be affected.'),
  );
  $form['sessions_keep_alive_interval'] = array(
    '#type' => 'textfield',
    '#title' => t('Interval'),
    '#default_value' => variable_get('sessions_keep_alive_interval', '15'),
    '#description' => t('Number of minutes between session .'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 */
function sessions_keep_alive_form_alter(&$form, &$form_state, $form_id) {
  $forms = str_replace(' ', '', variable_get('sessions_keep_alive_forms'));
  $form_array = explode(',', $forms);
  foreach ($form_array as $delta => $form_name) {
    if ($form_id == $form_name) {
      $form['#attached']['js'][] = drupal_get_path('module', 'sessions_keep_alive') . '/js/sessions-keep-alive.js';
      $form['#attached']['js'][] = array(
        'data' => array('session_keep_alive_interval' => variable_get('sessions_keep_alive_interval', '15')),
        'type' => 'setting',
      );
    }
  }
}
